spring:
  application:
    name: eureka-server
  security:
    user:
      name: lpf
      password: root

server.port: 9001

eureka:
  instance:
    hostname: eureka-9001.com
    instance-id: eureka-9001
  client:
    service-url:
      defaultZone: http://lpf:root@eureka-9002.com:9002/eureka,http://lpf:root@eureka-9003.com:9003/eureka

logging.level.root: info