server:
  port: 8080
spring:
  application:
    name: eureakServer8080

eureka:
  client:
    register-with-eureka: false  #表示是否将自己注册到 Eureka Server，默认为 true
    fetch-registry: false   #表示是否从 Eureka Server 获取注册信息，默认为 true
