server:
  port: 8092
spring:
  application:
    name: gateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: path_route
          uri: lb://provider
          filters:
            - AddRequestParameter=fool, bar
          predicates:
#            - After=2018-04-22T06:06:06+08:00[Asia/Shanghai]
#            - Before=2018-04-22T06:06:06+08:00[Asia/Shanghai]
#            - Between=2018-04-22T06:06:06+08:00[Asia/Shanghai], 2019-04-22T06:06:06+08:00[Asia/Shanghai]
            - Method=GET
#             - Path=/fool/{segment}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-9001.com:9001/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug

#gateway
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: path_route
#          uri: http://httpbin.org
#          predicates:
#            - Path=/get