server:
  port: 7005
spring:
  boot:
    admin:
      client:
        url: http://localhost:7004
  application:
    name: spring-boot-admin-client
management:
  endpoints:
    web:
      exposure:
        include: "*"