server:
  port: 8081
spring:
  application:
    name: eurekab

eureka:
  client:
    register-with-eureka: false  #表示是否将自己注册到 Eureka Server，默认为 true
    fetch-registry: false   #表示是否从 Eureka Server 获取注册信息，默认为 true
    service-url:
      defaultZone: http://eurekaa:8080/eureka/,http://eurekac:8082/eureka/
  instance:
    hostname: eurekab