spring:
  application:
    name: eureka-server
  security:
    user:
      name: lpf
      password: root

server.port: 9002

eureka:
  instance:
    hostname: eureka-9002.com
    instance-id: eureka-9002
  client:
    service-url:
      defaultZone: http://eureka-9001.com:9001/eureka,http://eureka-9003.com:9003/eureka

logging.level.root: info