spring:
  application:
    name: eureka-server
  security:
    user:
      name: lpf
      password: root

server.port: 9003

eureka:
  instance:
    hostname: eureka-9003.com
    instance-id: eureka-9003
  client:
    service-url:
      defaultZone: http://lpf:root@eureka-9001.com:9001/eureka,http://lpf:root@eureka-9002.com:9002/eureka

logging.level.root: info